name: Przedszkola - Production Deploy
on:
  workflow_dispatch: ~
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            sudo ./deploy2.sh
